# Generated by Django 4.2.5 on 2023-09-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_band'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'venue')},
        ),
    ]
